class CreateArtists < ActiveRecord::Migration[6.1]
  def change
    # create_table, remove_table, rename_table, remove_column, add_column
    create_table :artists do |t|
      t.string :name
      t.string :genre
      t.integer :age
      t.string :hometown
      #no need to specify id, automatically generated by activerecord as primary key
    end
  end
end
